apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: quarkus-api
          imagePullPolicy: Never
          image: quarkus/quarkus-api-jvm
          tag : "1.0"
          ports:
            - containerPort: 8080
  dependsOn:
    - {{ .Release.Name }}-redis-service

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: 8080
      nodePort: 30080
  type: NodePort
