apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:

    scrape_configs:

    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'quarkus-micrometer'
      metrics_path: '/q/metrics'
      scrape_interval: 3s
      static_configs:
        - targets: ['k8s-app-service:8080']